@startuml
'https://plantuml.com/class-diagram

'사이즈 증가'
scale 2

class Slime

class Hero extends Character{
    + hp: Int
    - name: String

    attack(slime: Slime)

}

class SuperHero extends Hero

abstract class Character{
    {abstract} + attack(slime: Slime)
}

@enduml